build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armhf: ghcr.io/home-assistant/armhf-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
  i386: ghcr.io/home-assistant/i386-base:latest
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: LiveKit Server"
  org.opencontainers.image.description: "LiveKit server for real-time video, audio and data communication with Matrix integration"
  org.opencontainers.image.source: "https://github.com/MichalTorma/ha-livekit"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.documentation: "https://github.com/MichalTorma/ha-livekit/blob/main/README.md"
args:
  LIVEKIT_VERSION: "1.7.2"
