name: "LiveKit Server"
description: "LiveKit server for real-time video, audio and data communication with Matrix integration"
version: "0.1.7"
slug: "livekit"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: manual
hassio_api: true
hassio_role: default
host_network: false
privileged: []
ports:
  7880/tcp: 7880
  7881/tcp: 7881
  # UDP ports for WebRTC media (subset of 40000-40099 range)
  40000/udp: 40000
  40001/udp: 40001
  40002/udp: 40002
  40003/udp: 40003
  40004/udp: 40004
  40005/udp: 40005
  40006/udp: 40006
  40007/udp: 40007
  40008/udp: 40008
  40009/udp: 40009
  40010/udp: 40010
  40011/udp: 40011
  40012/udp: 40012
  40013/udp: 40013
  40014/udp: 40014
  40015/udp: 40015
  40016/udp: 40016
  40017/udp: 40017
  40018/udp: 40018
  40019/udp: 40019
ports_description:
  7880/tcp: "LiveKit HTTP API and WebRTC"
  7881/tcp: "LiveKit RTC TCP port"
  40000/udp: "WebRTC media port"
  40001/udp: "WebRTC media port"
  40002/udp: "WebRTC media port"
  40003/udp: "WebRTC media port"
  40004/udp: "WebRTC media port"
  40005/udp: "WebRTC media port"
  40006/udp: "WebRTC media port"
  40007/udp: "WebRTC media port"
  40008/udp: "WebRTC media port"
  40009/udp: "WebRTC media port"
  40010/udp: "WebRTC media port"
  40011/udp: "WebRTC media port"
  40012/udp: "WebRTC media port"
  40013/udp: "WebRTC media port"
  40014/udp: "WebRTC media port"
  40015/udp: "WebRTC media port"
  40016/udp: "WebRTC media port"
  40017/udp: "WebRTC media port"
  40018/udp: "WebRTC media port"
  40019/udp: "WebRTC media port"
map:
  - config:rw
  - ssl:ro
  - data:rw
options:
  # Server Configuration
  domain: "homeassistant.local"
  http_port: 7880
  rtc_tcp_port: 7881
  # UDP port range for direct WebRTC media (avoid overlap with TURN server 49152-65535)
  rtc_udp_port_min: 40000
  rtc_udp_port_max: 40099
  
  # Authentication & Security
  api_key: ""
  api_secret: ""
  
  # SSL/TLS Configuration
  use_ssl: false
  cert_file: "fullchain.pem"
  pkey_file: "privkey.pem"
  
  # TURN Server Configuration (for integration with Coturn)
  turn_enabled: true
  turn_servers:
    - "turn:homeassistant.local:3478"
  turn_username: ""
  turn_password: ""
  turn_static_auth_secret: ""
  
  # Matrix Integration
  matrix_homeserver_url: ""
  matrix_widget_url: ""
  
  # Logging
  log_level: "info"
  verbose: false
  
  # Advanced Settings
  external_ip: ""
  use_ice_lite: false
  webhook_urls: []

schema:
  # Server Configuration
  domain: "str"
  http_port: "port"
  rtc_tcp_port: "port"
  rtc_udp_port_min: "port"
  rtc_udp_port_max: "port"
  
  # Authentication & Security
  api_key: "str"
  api_secret: "password"
  
  # SSL/TLS Configuration
  use_ssl: "bool"
  cert_file: "str?"
  pkey_file: "str?"
  
  # TURN Server Configuration
  turn_enabled: "bool"
  turn_servers: ["str"]
  turn_username: "str?"
  turn_password: "password?"
  turn_static_auth_secret: "password?"
  
  # Matrix Integration
  matrix_homeserver_url: "url?"
  matrix_widget_url: "url?"
  
  # Logging
  log_level: "list(debug|info|warn|error)"
  verbose: "bool"
  
  # Advanced Settings
  external_ip: "str?"
  use_ice_lite: "bool"
  webhook_urls: ["url?"]
